version: "3.8"
services:
  
  caddy:
    image: caddy:latest
    container_name: caddy_social
    restart: unless-stopped
    ports:
      - "444:443"
    volumes:
      - ./docker/caddy/social.com+4.pem:/etc/cert/social/social.com+4.pem
      - ./docker/caddy/social.com+4-key.pem:/etc/cert/social/social.com+4-key.pem
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - .:/srv
      - caddy_data:/data
      - caddy_config:/config

  
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web_social
    volumes:
      - .:/srv
    

  database:
    container_name: postgres_social
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: social
      POSTGRES_USER: social
      POSTGRES_DB: social
      
  pgadmin:
    container_name: pgadmin_social
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    links:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    
  

volumes:
  caddy_data:
  caddy_config:
    